name: "ci-linter"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write

jobs:
  clippy:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: check-clippy
        uses: auguwu/clippy-action@1.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check-args: --all-features --all-targets --workspace
